
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use secret in a script
      run: echo "The secret is ${{ secrets.MY_SECRET }}"
    - name: Use secret as an environment variable
      run: echo "The secret is $MY_SECRET"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}